[tool.poetry]
name = "my-dev-setting"
version = "0.1.0"
description = ""
authors = ["Kanghyun Kim <kh11kim@kaist.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
